name: food_dash
description: "A new Flutter project."
publish_to: 'https://pub.dev'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  firebase_core: ^3.1.1
  http_parser: ^4.0.2
  leak_tracker: ^10.0.4
  leak_tracker_flutter_testing: ^3.0.3
  lints: ^4.0.0
  material_color_utilities: ^0.8.0
  meta: ^1.12.0
  test_api: ^0.7.0
  vm_service: ^14.2.1
  typed_data: ^1.3.2
  get: ^4.6.6
  cupertino_icons: ^1.0.6
  line_awesome_flutter: ^3.0.1
  firebase_auth: ^5.1.1
  firebase_auth_web: ^5.12.3
  firebase_auth_platform_interface: ^7.4.1
  google_sign_in: ^6.2.1
  google_sign_in_ios: ^5.7.6
  google_sign_in_web: ^0.12.4+1
  http: ^1.0.0
  cloud_firestore: ^5.0.2
  image_picker: ^0.8.7+5
  firebase_database: ^11.0.2
  firebase_storage: ^12.1.0
  geolocator: 12.0.0
  google_maps_flutter: ^2.1.0
  flutter_dotenv: ^5.0.2
  intl: ^0.18.0
  math_expressions: ^2.2.0
  stripe_payment: ^1.1.0
  path_drawing: ^1.0.1
  path_provider: ^2.0.1
  provider: ^6.1.2
  path_parsing: ^1.0.1
  petitparser: ^6.0.2
  xml: ^6.5.0
  flutter_svg: ^2.0.10+1
  firebase_messaging: ^15.0.3
  flutter_local_notifications: ^17.2.1+2
  cached_network_image: ^3.0.0
  flutter_facebook_auth: ^7.0.1
 

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  font_awesome_flutter: ^10.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  
  image_path: "lib/assets/deliveryicon.png"

  web:
    generate: true
    image_path: "lib/assets/deliveryicon.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/deliveryicon.png
    - lib/assets/default.jpg
